log_level = "warn"
outputs = { Targets = ["eDP-1"] }
position = "Top"
app_launcher_cmd = "wofi --show drun"

[modules]
left = [ "appLauncher", [ "Workspaces" ], [ "WindowTitle" ] ]
center = ["clipboard"]
right = [ "SystemInfo", [  "Tray" ], "Clock", "Privacy", "Settings" ]

[workspaces]
enable_workspace_filling = false

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "wofi --show drun"

[window_title]
truncate_title_after_length = 50

[clock]
format = "󰃭  %D %R"

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[appearance]
opacity = 0.8
primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
